#!/usr/bin/env python3
"""sync-member-workflows.py - each member's own .github/workflows/, DERIVED
from the root workflows rather than copied once and left to rot.

WHY THIS EXISTS. GitHub Actions runs only the workflows at a repository's
root, so in this monorepo every member's .github/workflows/ is inert, and
each one was a snapshot of that member's pre-suite CI: the shape it had the
day it was folded in. Measured on 2026-09-21, the six native members' copies
differed from the root native-<member>.yml lanes that actually run by
216 to 445 diff lines each - no macOS universal lanes, no manylinux
containers, commit-binaries jobs the suite deliberately removed, and, for
coinxt, none of the committed-library execution the root lane gained. Every
member is on its way to being its own repository (docs/MEMBER-REPO-SPLIT.md),
and the day it moves, the workflow that fires is the inert copy. A repository
whose first CI run is a year-old matrix is not "ready to go".

WHAT IT DOES. For every member in tools/member-registry.py it writes two
files under <member>/.github/workflows/:

  native.yml  (native members only) - the root .github/workflows/
              native-<member>.yml with exactly the monorepo-isms removed:
              the `paths:` filters (a standalone repository IS the member,
              so every push is in scope), the `working-directory: <member>`
              defaults (the checkout root is the member root there), and
              the `<member>/` prefix on artifact paths and the one docker
              `-w /io/<member>`. Nothing else changes - the lanes, flags,
              runners and assertions are the ones the suite runs today.
              Each rewrite ASSERTS it fired, so a root lane that stops
              using the shape this tool expects fails the build here rather
              than shipping a workflow with a phantom directory in it.
  gates.yml   (every member) - the compiler-free gate job: check out the
              member, check out the sibling members its gates reach into
              (from the registry, as ../<name> beside it - the layout
              tools/run-gates.sh and the sibling helpers expect), and run
              tools/run-gates.sh with XTALK_REQUIRE_SIBLINGS=1 so a missing
              sibling is a red job rather than a quiet skip.

`--check` re-derives both and fails if the tree's copies differ, or if a
member's .github/workflows/ holds any file this tool did not generate (a
stale pre-suite copy would otherwise sit beside the derived one and fire too,
in the standalone repository). It runs in tools/build-all.sh's suite block.

    python3 tools/sync-member-workflows.py           # write
    python3 tools/sync-member-workflows.py --check   # gate

The generated files carry a header saying so. Edit the ROOT workflow (or
this generator, or the registry) and re-run; a hand edit inside a member's
copy is undone by the next run and refused by --check until then.
"""

import importlib.util
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


REG = _load("member_registry", os.path.join(HERE, "member-registry.py"))

GENERATED_MARK = "GENERATED by tools/sync-member-workflows.py"


# ---------------------------------------------------------------------------
# native.yml: the root lane minus the monorepo-isms
# ---------------------------------------------------------------------------

def native_header(m):
    return """# %s
# from the suite's .github/workflows/native-%s.yml (%s).
#
# This is %s's native build matrix as its OWN repository runs it. Inside the
# suite monorepo this file is inert (GitHub Actions reads only the root
# .github/workflows/), and the root copy is the one that fires there; the two
# are held identical up to the monorepo-isms by the generator's --check in the
# suite's gate set, so the lanes, flags, runners and assertions here are the
# ones the suite runs, not a snapshot of them.
#
# What the generator removed, and why each removal is right for a standalone
# repository: the `paths:` filters (this repository IS the member, so every
# push is in scope), the `working-directory: %s` defaults (the checkout root
# is the member root here), and the `%s/` prefix on artifact paths.
#
# Do not edit this file by hand: edit the root workflow in the suite and
# re-run `python3 tools/sync-member-workflows.py`. After the split, this file
# becomes the member's own and the note above becomes history.
""" % (GENERATED_MARK, m.name, REG.SUITE_URL, m.title, m.name, m.name)


def derive_native(m, text):
    """Apply the rewrites, each asserted to fire (a rewrite that matched
    nothing is a root lane that changed shape, and the generator must say
    so rather than emit a workflow with a phantom directory in it)."""
    lines = text.split("\n")
    # 1. the header comment: everything before the first `name:` line.
    try:
        first = next(i for i, l in enumerate(lines) if l.startswith("name: "))
    except StopIteration:
        raise SystemExit("%s: no top-level `name:` line" % m.name)
    body = lines[first:]
    fired = {"paths": 0, "working-directory": 0, "path-prefix": 0}

    # 2. the `paths:` filters under on.pull_request / on.push. The block is
    #    `    paths:` followed by `      - "..."` entries.
    out = []
    i = 0
    while i < len(body):
        l = body[i]
        if l == "    paths:":
            fired["paths"] += 1
            i += 1
            while i < len(body) and body[i].startswith('      - "'):
                i += 1
            continue
        out.append(l)
        i += 1
    body = out

    # 3. `working-directory: <m>` defaults, top-level and per-job. Each is a
    #    three-line block `defaults:` / `run:` / `working-directory: <m>` at
    #    one indentation, possibly followed by a blank line.
    out = []
    i = 0
    while i < len(body):
        l = body[i]
        ind = len(l) - len(l.lstrip(" "))
        if (l.strip() == "defaults:" and i + 2 < len(body)
                and body[i + 1].strip() == "run:"
                and body[i + 2].strip() == "working-directory: " + m.name
                and len(body[i + 1]) - len(body[i + 1].lstrip(" ")) == ind + 2
                and len(body[i + 2]) - len(body[i + 2].lstrip(" ")) == ind + 4):
            fired["working-directory"] += 1
            i += 3
            if ind == 0 and i < len(body) and body[i] == "":
                i += 1   # the blank line after a top-level block
            continue
        out.append(l)
        i += 1
    body = out

    # 4. artifact paths: `path: <m>/...` -> `path: ...`.
    out = []
    pat = re.compile(r"^(\s+path: )" + re.escape(m.name) + r"/")
    for l in body:
        n = pat.sub(r"\1", l)
        if n != l:
            fired["path-prefix"] += 1
        out.append(n)
    body = out

    # 5. box2dxt's manylinux container mounts the checkout at /io and cd's
    #    into the member; standalone, /io is the member.
    body = [l.replace("-w /io/" + m.name + " ", "-w /io ") for l in body]

    for k, v in fired.items():
        if v == 0:
            raise SystemExit("%s: the %r rewrite matched nothing in "
                             "native-%s.yml - the root lane changed shape; "
                             "teach the generator before shipping a copy"
                             % (m.name, k, m.name))
    if fired["paths"] != 2:
        raise SystemExit("%s: expected two `paths:` filters (pull_request "
                         "and push), found %d" % (m.name, fired["paths"]))

    result = native_header(m) + "\n".join(body)
    # No member-prefixed PATH may survive outside a comment. Filenames like
    # coinxt.so and native/coinxt.c are not paths INTO the member, and this
    # asks about the directory form only.
    leak = re.compile(r"(^|[\s\"'=:])" + re.escape(m.name) + r"/")
    for n, l in enumerate(result.split("\n"), 1):
        if l.lstrip().startswith("#"):
            continue
        if leak.search(l):
            raise SystemExit("%s: line %d of the derived native.yml still "
                             "names %s/ - a monorepo path the generator does "
                             "not know how to rewrite: %s"
                             % (m.name, n, m.name, l.strip()))
    return result + ("" if result.endswith("\n") else "\n")


# ---------------------------------------------------------------------------
# gates.yml: the member's own gates, with its siblings beside it
# ---------------------------------------------------------------------------

def gates_yml(m):
    sibs = REG.siblings_of(m.name)
    lines = []
    w = lines.append
    w("# %s" % GENERATED_MARK)
    w("# (%s; the registry row is tools/member-registry.py)." % REG.SUITE_URL)
    w("#")
    w("# %s's compiler-free gates, as its OWN repository runs them on every" % m.title)
    w("# push: `bash tools/run-gates.sh`, the member's own list. Inside the suite")
    w("# monorepo this file is inert (GitHub Actions reads only the root")
    w("# .github/workflows/), and tools/build-all.sh --gates runs the same script")
    w("# there. There is no headless way to compile or run a .livecodescript, so")
    w("# these are the static gates plus every known-answer, golden and")
    w("# execution-gate check that CAN run without an engine; anything visual,")
    w("# timed or extension-touching stays 'verified statically; needs an OXT")
    w("# pass' (the honesty convention).")
    if sibs:
        w("#")
        w("# THE SIBLING CHECKOUTS. Some of this member's gates reach into sibling")
        w("# members (%s) - a committed binary to execute against, an" % ", ".join(sibs))
        w("# interpreter or a boot runner to reuse rather than copy. The tools find")
        w("# them as ../<name> beside the member, so this job checks the member out")
        w("# into a directory named after it and each sibling beside it, from that")
        w("# sibling's own repository at its default branch. XTALK_REQUIRE_SIBLINGS")
        w("# turns 'sibling absent, tier skipped' into a failure: in CI a skip and a")
        w("# pass both exit 0, and a lane that can pass by measuring nothing is the")
        w("# shape this family's tests/cross-member-test.py records.")
    w("#")
    w("# Do not edit by hand: edit tools/member-registry.py or the generator in")
    w("# the suite and re-run `python3 tools/sync-member-workflows.py`.")
    w("name: gates")
    w("")
    w("on:")
    w("  push:")
    w("  pull_request:")
    w("  workflow_dispatch:")
    w("")
    w("permissions:")
    w("  contents: read")
    w("")
    w("jobs:")
    w("  gates:")
    w("    name: static gates + golden vectors + execution gates")
    w("    runs-on: ubuntu-latest")
    if m.name == "coinxt":
        w("    # The wallet gates alone take hours (tools/run-gates.sh says why and")
        w("    # runs the three at once); the default six-hour ceiling is stated so")
        w("    # nobody lowers it without reading this.")
        w("    timeout-minutes: 360")
    if sibs:
        w("    defaults:")
        w("      run:")
        w("        working-directory: %s" % m.name)
    w("    steps:")
    if sibs:
        w("      - uses: actions/checkout@v4")
        w("        with:")
        w("          path: %s" % m.name)
        for s in sibs:
            sm = REG.BY_NAME[s]
            w("      - name: Check out %s beside it (%s)" % (s, sm.repo))
            w("        uses: actions/checkout@v4")
            w("        with:")
            w("          repository: %s" % sm.repo)
            w("          path: %s" % s)
    else:
        w("      - uses: actions/checkout@v4")
    w("      - uses: actions/setup-python@v5")
    w("        with:")
    w('          python-version: "3.x"')
    if m.name == "coinxt":
        w("      # coin-kat.py cross-checks the curve vectors against an INDEPENDENT")
        w("      # implementation and SKIPS that leg without it; COINXT_REQUIRE_CROSSCHECK")
        w("      # below turns the skip into a failure, so deleting this install can")
        w("      # never quietly downgrade the gate.")
        w("      - name: Install the independent crypto implementation coinxt checks against")
        w("        run: pip install ecdsa")
    w("      - name: Run the member's own gates")
    env = []
    if sibs:
        env.append(('XTALK_REQUIRE_SIBLINGS', '"1"'))
    if m.name == "coinxt":
        env.append(('COINXT_REQUIRE_CROSSCHECK', '"1"'))
    if env:
        w("        env:")
        for k, v in env:
            w("          %s: %s" % (k, v))
    w("        run: bash tools/run-gates.sh")
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------

def expected_files():
    """{member: {filename: text}} for every member in the registry."""
    out = {}
    for m in REG.MEMBERS:
        files = {}
        if m.native:
            src = os.path.join(ROOT, ".github", "workflows",
                               "native-%s.yml" % m.name)
            if not os.path.exists(src):
                raise SystemExit("%s: registry says native=True but %s does "
                                 "not exist" % (m.name, os.path.relpath(src, ROOT)))
            with open(src, encoding="utf-8") as fh:
                files["native.yml"] = derive_native(m, fh.read())
        files["gates.yml"] = gates_yml(m)
        out[m.name] = files
    return out


def validate_yaml(text, label):
    try:
        import yaml
    except ImportError:
        return
    try:
        doc = yaml.safe_load(text)
    except Exception as e:      # noqa: BLE001 - report, then fail
        raise SystemExit("%s: generated YAML does not parse: %s" % (label, e))
    # PyYAML reads the bare `on:` key as the boolean True; either spelling
    # must be present, with jobs beside it.
    if not (("on" in doc or True in doc) and "jobs" in doc):
        raise SystemExit("%s: generated YAML lacks on:/jobs:" % label)


def main(argv):
    check = "--check" in argv
    want = expected_files()
    problems = []
    written = 0
    for m in REG.MEMBERS:
        wdir = os.path.join(m.path, ".github", "workflows")
        files = want[m.name]
        for name, text in files.items():
            validate_yaml(text, "%s/%s" % (m.name, name))
            path = os.path.join(wdir, name)
            rel = os.path.relpath(path, ROOT)
            cur = None
            if os.path.exists(path):
                with open(path, encoding="utf-8") as fh:
                    cur = fh.read()
            if cur == text:
                continue
            if check:
                problems.append("%s is %s - run `python3 tools/"
                                "sync-member-workflows.py`"
                                % (rel, "stale" if cur is not None else "missing"))
            else:
                os.makedirs(wdir, exist_ok=True)
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(text)
                written += 1
                print("wrote %s" % rel)
        # Nothing else may live there: a stale pre-suite copy beside the
        # derived one would fire too, in the standalone repository.
        if os.path.isdir(wdir):
            for name in sorted(os.listdir(wdir)):
                if name not in files:
                    problems.append("%s/.github/workflows/%s is not generated by "
                                    "this tool - a stale copy that would fire "
                                    "beside the derived workflows; delete it"
                                    % (m.name, name))
    if problems:
        print("sync-member-workflows: %d problem(s)" % len(problems))
        for p in problems:
            print("  - " + p)
        return 1
    n = sum(len(v) for v in want.values())
    if check:
        print("sync-member-workflows: OK (%d workflow(s) across %d members "
              "match what the root workflows and the registry derive)"
              % (n, len(want)))
    else:
        print("sync-member-workflows: %d file(s) written, %d already current"
              % (written, n - written))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
