#!/usr/bin/env python3
"""sync-member-readmes.py - the "Relationship to the xTalk suite" section of
every member README, DERIVED from the registries rather than written once.

WHY THIS EXISTS. Each member is published into a repository of its own
(tools/publish-members.py; docs/MEMBER-REPO-SPLIT.md). A reader arriving at
that repository needs four things its README did not say on 2026-09-21:
where the member is developed (the suite, permanently, since the 2026-09-22
decision - so also how a contribution made there comes home) and where its
suite-level citations (`docs/OXT-ENGINE-NOTES.md`,
`tools/build-all.sh`, `../coinxt/...`) resolve; which SIBLING members its
gates need beside it and how to point them there; which CARRIED COPIES it
holds (the UI kit, the boot self-check, the harness scaffold, sibling
libraries embedded into its demos, the unified checker) and where the
masters and drift gates for those live, since none of that machinery
travels with the member; and what its own gate runner cannot check alone.

Every one of those facts already lives in a registry in tools/ - the member
table, sync-demo-embeds.py's REGISTRY, the three drift gates' adopter lists,
check-checker-drift.py's copy sets. Writing them into eleven READMEs by hand
is how the root README's coverage ratio and the ABI numbers went stale, so
this tool reads the registries and writes the section between two HTML
comment sentinels (invisible when rendered), and --check refuses a README
whose section is not what the registries derive. Edit the registries, not
the section.

    python3 tools/sync-member-readmes.py           # write
    python3 tools/sync-member-readmes.py --check   # gate (in build-all.sh)

The section is ASCII with plain hyphens, because four members run
check-docs-style.py over their own prose and this text lands in theirs.
"""

import importlib.util
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


REG = _load("member_registry", os.path.join(HERE, "member-registry.py"))
EMBEDS = _load("sync_demo_embeds", os.path.join(HERE, "sync-demo-embeds.py"))
UIKIT = _load("check_ui_kit_drift", os.path.join(HERE, "check-ui-kit-drift.py"))
SELFCHECK = _load("check_demo_selfcheck_drift",
                  os.path.join(HERE, "check-demo-selfcheck-drift.py"))
SCAFFOLD = _load("check_harness_scaffold_drift",
                 os.path.join(HERE, "check-harness-scaffold-drift.py"))
CHECKER = _load("check_checker_drift",
                os.path.join(HERE, "check-checker-drift.py"))

BEGIN = ("<!-- ==== SUITE RELATIONSHIP BEGIN (generated by "
         "tools/sync-member-readmes.py in the xTalk suite from "
         "tools/member-registry.py and the carried-copy registries; "
         "do not edit inside the markers) ==== -->")
END = "<!-- ==== SUITE RELATIONSHIP END ==== -->"

# Why each sibling is needed, per (member, sibling). Prose, because the
# registry records the edge and a reader wants the reason.
WHY = {
    ("nostrxt", "coinxt"): "the committed x86_64-linux binary, which tier 2 of "
                           "`tools/check-script-vectors.py` executes the "
                           "composed paths against",
    ("nostrxt", "sodiumxt"): "the committed x86_64-linux binary, for the "
                             "NIP-44 cipher seam in the same tier",
    ("riptide", "nostrxt"): "`tools/lcs-interp.py` (the family interpreter, "
                            "loaded rather than copied), the nostrxt library "
                            "the bridge is written over, and the "
                            "`nostr_reference.py` oracle",
    ("riptide", "coinxt"): "the committed x86_64-linux binary, for the "
                           "signing paths",
    ("coinxt", "riptide"): "`tools/check-demo-boot.py`, the headless boot "
                           "runner that `tools/check-wallet-boot.py` REUSES "
                           "rather than copies",
    ("coinxt", "nostrxt"): "`tools/lcs-interp.py` and the oracle that "
                           "riptide's runner loads at import time",
    ("nocloud", "riptide"): "`tools/check-demo-boot.py`, the boot runner "
                            "`tools/check-script-vectors.py` drives the "
                            "helpers through",
    ("nocloud", "nostrxt"): "what riptide's runner loads at import time",
    ("nocloud", "coinxt"): "what riptide's runner loads at import time",
    ("holde-em", "riptide"): "`tools/check-demo-boot.py` and "
                             "`tools/riptide_reference.py`, which "
                             "`tools/check-script-vectors.py` drives the "
                             "stack through",
    ("holde-em", "nostrxt"): "what riptide's runner loads at import time",
    ("holde-em", "coinxt"): "what riptide's runner loads at import time",
    ("torrentxt", "riptide"): "`tools/check-demo-boot.py`, the runner "
                              "`tools/check-script-vectors.py` drives the "
                              "demos' Model C handlers through",
    ("torrentxt", "nostrxt"): "what riptide's runner loads at import time",
    ("torrentxt", "sodiumxt"): "the committed x86_64-linux binary, which tier 2 "
                               "of `tools/check-script-vectors.py` runs the "
                               "verifier and the M9 feed-seal KAT on",
}


def _mine(rel, m):
    return rel.replace(os.sep, "/").startswith(m.name + "/")


def _strip(rel, m):
    return rel.replace(os.sep, "/")[len(m.name) + 1:]


def section(m):
    sibs = REG.siblings_of(m.name)
    o = []
    w = o.append
    w(BEGIN)
    w("")
    w("## Relationship to the xTalk suite")
    w("")
    w("%s is developed in the **xTalk suite** monorepo at %s, as its"
      % (m.title, REG.SUITE_URL))
    w("`%s/` member, and PUBLISHED from there into this repository," % m.name)
    w("https://github.com/%s: once a change lands on the suite's `main` and"
      % m.repo)
    w("the suite's gates pass, the suite's `tools/publish-members.py` replays it")
    w("here as a commit carrying a `Suite-Commit:` trailer that names the suite")
    w("commit it came from. The suite is the source of truth; this repository is")
    w("its published copy, one commit for each change to `%s/` that landed on" % m.name)
    w("the suite's `main`.")
    w("")
    w("**Contributing.** Please open issues and pull requests at the suite. A pull")
    w("request opened here is not lost - the suite brings it home with")
    w("`python3 tools/publish-members.py port %s --ref pull/<n>/head`, keeping its"
      % m.name)
    w("author - but a commit made here directly holds up the next publish until")
    w("it has been ported, because publishing never overwrites work it did not")
    w("write. The suite's `docs/MEMBER-REPO-SPLIT.md` is the whole workflow.")
    w("")
    w("**Suite-level paths cited from here.** This member's `CLAUDE.md` and")
    w("`docs/` cite files that live at the suite root, not in this tree:")
    w("`docs/OXT-ENGINE-NOTES.md` (engine behaviour, the authoritative list),")
    w("`docs/OXT-PASS-RUNBOOK.md`, `tools/build-all.sh`,")
    w("`tests/suite-selftest.livecodescript` and the suite-level `docs/`")
    w("index. Read them at `%s/blob/main/<path>`. A path of the"
      % REG.SUITE_URL)
    w("form `../<member>/...` names a sibling member of the suite; each has its")
    w("own repository, listed in `tools/member-registry.py` there.")
    w("")
    if sibs:
        w("**Sibling members this member's gates need beside it.** `bash")
        w("tools/run-gates.sh` (this member's own gate list, the one CI runs)")
        w("reaches into these siblings, found as `../<name>` beside this checkout:")
        w("")
        for s in sibs:
            sm = REG.BY_NAME[s]
            w("- `../%s` from https://github.com/%s - %s."
              % (s, sm.repo, WHY[(m.name, s)]))
        w("")
        w("Clone them beside this checkout under exactly those directory names")
        w("(and keep this checkout named `%s`), or point `XTALK_SIBLINGS` at a"
          % m.name)
        w("directory holding them (`XTALK_SIBLING_<NAME>` for one). The generated")
        w("`.github/workflows/gates.yml` takes them from the suite itself, at the")
        w("commit named by this repository's newest `Suite-Commit:` trailer - the")
        w("versions the suite's gates ran with this tree - and sets")
        w("`XTALK_REQUIRE_SIBLINGS=1` so a missing sibling fails the job rather")
        w("than skipping its tier. Nothing the SHIPPED code needs is beside it: a")
        w("demo that uses a sibling's library carries its own copy (below).")
    else:
        w("**Sibling members this member's gates need beside it.** None: `bash")
        w("tools/run-gates.sh` (this member's own gate list, the one CI runs)")
        w("needs nothing but this checkout and Python 3.")
    w("")
    # --- carried copies ---------------------------------------------------
    w("**Carried copies inside this member, and where their masters are.**")
    w("Every runnable stack here is one paste-and-run file, so it carries what")
    w("it needs verbatim between marker lines. The masters, and the drift gates")
    w("that hold every copy byte-identical to them, live in the suite and do")
    w("not travel with this member; refresh a copy from the suite (the marker")
    w("lines name the master) rather than editing inside the markers.")
    w("")
    kit = [_strip(r, m) for r in UIKIT.ADOPTERS if _mine(r, m)]
    sc = [_strip(r, m) for r in sorted(SELFCHECK.ADOPTERS) if _mine(r, m)]
    sf = [_strip(r, m) for r in SCAFFOLD.ADOPTERS if _mine(r, m)]
    if kit:
        w("- The demo UI kit (`tools/ui-kit.livecodescript`; gate"
          " `tools/check-ui-kit-drift.py`) in %s." % ", ".join("`%s`" % k for k in kit))
    if sc:
        w("- The boot self-check block (`tools/demo-selfcheck.livecodescript`;"
          " gate `tools/check-demo-selfcheck-drift.py`) in %s."
          % ", ".join("`%s`" % k for k in sc))
    if sf:
        w("- The self-test harness scaffold (`tools/harness-scaffold.livecodescript`;"
          " gate `tools/check-harness-scaffold-drift.py`) in %s."
          % ", ".join("`%s`" % k for k in sf))
    embeds = []
    for demo, providers in sorted(EMBEDS.REGISTRY.items()):
        if not _mine(demo, m):
            continue
        for p in providers:
            if _mine(p, m):
                continue
            embeds.append((_strip(demo, m), p, p.split("/")[0]))
    own = []
    for demo, providers in sorted(EMBEDS.REGISTRY.items()):
        if not _mine(demo, m):
            continue
        for p in providers:
            if _mine(p, m):
                own.append((_strip(demo, m), _strip(p, m)))
    if embeds:
        w("- Sibling libraries embedded by the suite's `tools/sync-demo-embeds.py`"
          " (the copy is the shipped file; the master is the sibling's `src/`):")
        for demo, p, owner in embeds:
            w("  - `%s` carries `%s` from https://github.com/%s."
              % (demo, p, REG.BY_NAME[owner].repo))
    if own:
        w("- This member's own library, embedded into its own stacks by the same"
          " tool so each is one file to paste: %s."
          % "; ".join("`%s` carries `%s`" % (d, p) for d, p in own))
    for demo, reason in sorted(EMBEDS.NOT_EMBEDDED.items()):
        if _mine(demo, m):
            w("- `%s` deliberately embeds nothing: %s" % (_strip(demo, m), reason))
    copies = [name for name, members in sorted(CHECKER.COPY_SETS.items())
              if m.name in members]
    templ = [name for name, members in sorted(CHECKER.TEMPLATE_SETS.items())
             if m.name in members]
    parts = ["`tools/%s`" % c for c in copies] + ["`templates/%s`" % t for t in templ]
    if parts:
        w("- %s: byte-identical copies of the family's unified tooling, held"
          " identical across members by the suite's `tools/check-checker-drift.py`"
          " and fixture-tested there by `tools/test-checker.py`." % ", ".join(parts))
    w("")
    # --- what this member provides ----------------------------------------
    provided = []
    for demo, providers in sorted(EMBEDS.REGISTRY.items()):
        if _mine(demo, m):
            continue
        for p in providers:
            if _mine(p, m):
                provided.append((demo, _strip(p, m)))
    if provided:
        w("**What other members carry from this one.** The suite embeds this")
        w("member's script into the stacks below, verbatim; a change to it")
        w("reaches them when the suite re-runs `tools/sync-demo-embeds.py`, and")
        w("is not done until every carrier has been re-run on an engine:")
        w("")
        for demo, p in provided:
            w("- `%s` in %s carries `%s`." % (demo, demo.split("/")[0], p)
              if not demo.startswith("tests/") else
              "- the suite's `%s` carries `%s`." % (demo, p))
        w("")
    # --- what cannot be checked alone --------------------------------------
    w("**What this repository cannot check on its own.** The suite-wide gates -")
    w("cross-library name disjointness (`tools/check-cross-library-names.py`),")
    w("the carried-copy drift gates above, embed freshness, the cross-member")
    w("handler-call and typed-boundary checks (`tools/check-handler-calls.py`,")
    w("`tools/check-lcb-call-types.py`), the timer-pin closure, and the suite")
    w("paste's coverage ratchet (`tools/check-suite-coverage.py`) - run only in")
    w("the suite. `tools/run-gates.sh` here is this member's own list, and the")
    w("suite's `tools/build-all.sh` runs that same script, so the two cannot")
    w("disagree about what this member's gates are.")
    w("")
    w(END)
    return "\n".join(o) + "\n"


def splice(text, sec):
    """Replace the section between the sentinels, or append it."""
    if BEGIN in text and END in text:
        a = text.index(BEGIN)
        b = text.index(END) + len(END)
        # keep exactly one newline after END
        rest = text[b:].lstrip("\n")
        return text[:a] + sec + ("\n" + rest if rest else "")
    if BEGIN in text or END in text:
        raise SystemExit("a README has one sentinel without the other")
    body = text.rstrip("\n")
    return body + "\n\n" + sec


def main(argv):
    check = "--check" in argv
    problems = []
    written = 0
    for m in REG.MEMBERS:
        path = os.path.join(m.path, "README.md")
        rel = os.path.relpath(path, ROOT)
        if not os.path.exists(path):
            problems.append("%s is missing" % rel)
            continue
        with open(path, encoding="utf-8") as fh:
            cur = fh.read()
        sec = section(m)
        for ch in sec:
            if ord(ch) > 126:
                raise SystemExit("generated section for %s is not ASCII "
                                 "(check-docs-style would refuse it)" % m.name)
        want = splice(cur, sec)
        if want == cur:
            continue
        if check:
            problems.append("%s: the suite-relationship section is %s - run "
                            "`python3 tools/sync-member-readmes.py`"
                            % (rel, "stale" if BEGIN in cur else "missing"))
        else:
            with open(path, "w", encoding="utf-8") as fh:
                fh.write(want)
            written += 1
            print("wrote %s" % rel)
    if problems:
        print("sync-member-readmes: %d problem(s)" % len(problems))
        for p in problems:
            print("  - " + p)
        return 1
    if check:
        print("sync-member-readmes: OK (%d README section(s) match what the "
              "registries derive)" % len(REG.MEMBERS))
    else:
        print("sync-member-readmes: %d file(s) written, %d already current"
              % (written, len(REG.MEMBERS) - written))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
